name: Run training on push

on:
  push:
    branches:
      - kernelridge
      - dtree
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Decision Tree training
        run: python train.py
      - name: Run KernelRidge training
        run: python train2.py
